
services:
  lookup-cli-service:
    image: lookup-cli:latest
    container_name: lookup-cli-container
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../config/data.yaml:/app/config/data.yaml  # mount YAML file
    environment:
      - CONFIG_PATH=/app/config/data.yaml  # Env to yaml file path
    stdin_open: true
    tty: true
    command: ["tail", "-f", "/dev/null"]