#!/usr/bin/env python3
import sys
from config_reader import ConfigReader
import os
file_path = os.path.dirname(os.path.abspath(__file__))


def print_usage():
    """print user manual"""
    print("Usage: lookup-cli <name> <output_field>")


def main():
    # Detect length of args
    if len(sys.argv) != 3:
        print_usage()
        sys.exit(1)

    # Read args
    name = sys.argv[1]
    output_field = sys.argv[2]

    # Use Environment Variable or default value to locate YAML file
    config_path = os.getenv("CONFIG_PATH", f"{file_path}/../config/data.yaml")

    # Init ConfigReader
    try:
        reader = ConfigReader(f"{config_path}")
        data = reader.get_data()
    except FileNotFoundError as e:
        print(e)
        sys.exit(1)
    except RuntimeError as e:
        print(e)
        sys.exit(1)

    # Find Name
    person = next((item for item in data if item.get('name') == name), None)

    if not person:
        print("Name not found")
        sys.exit(1)

    # Find Field
    if output_field not in person:
        print("Field not found")
    else:
        print(person[output_field])


if __name__ == "__main__":
    main()